"""initial postgres workflow schema

Revision ID: b69c7b913125
Revises:
Create Date: 2026-07-16 01:12:32.467519
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "b69c7b913125"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deletion_audit_tombstones",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("replay_hash", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id"),
    )
    op.create_table(
        "owners",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("secret_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("secret_hash"),
    )
    op.create_table(
        "cases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("source_tier", sa.String(length=32), nullable=False),
        sa.Column("original_a", sa.Integer(), nullable=False),
        sa.Column("original_b", sa.Integer(), nullable=False),
        sa.Column("observed_work", sa.Text(), nullable=False),
        sa.Column("deidentified_attestation", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("original_a BETWEEN -12 AND 12", name="ck_cases_original_a"),
        sa.CheckConstraint("original_b BETWEEN -12 AND 12", name="ck_cases_original_b"),
        sa.ForeignKeyConstraint(["owner_id"], ["owners.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cases_owner_id"), "cases", ["owner_id"], unique=False)
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("scope", sa.String(length=160), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["owners.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "scope", "key_hash", name="uq_idempotency_owner_scope_key"),
    )
    op.create_index(
        op.f("ix_idempotency_records_expires_at"),
        "idempotency_records",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_idempotency_records_owner_id"), "idempotency_records", ["owner_id"], unique=False
    )
    op.create_table(
        "workflows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "CREATED",
                "ANALYZING",
                "PROBE_READY",
                "AWAITING_RESPONSE",
                "RESPONSE_RECORDED",
                "RESUME_PENDING",
                "UPDATING",
                "AWAITING_REVIEW",
                "APPROVED",
                "EDITED",
                "REJECTED",
                "ABSTAINED",
                "FAILED",
                name="workflowstate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=40), nullable=False),
        sa.Column("registry_version", sa.String(length=40), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("compiler_version", sa.String(length=48), nullable=False),
        sa.Column("model_snapshot", sa.String(length=120), nullable=True),
        sa.Column("model_request_id", sa.String(length=160), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["owners.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id"),
        sa.UniqueConstraint("thread_id"),
    )
    op.create_index(op.f("ix_workflows_owner_id"), "workflows", ["owner_id"], unique=False)
    op.create_table(
        "accepted_hypotheses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("template_id", sa.String(length=64), nullable=False),
        sa.Column("evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.String(length=280), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("truth_table_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id", "rank", name="uq_hypothesis_workflow_rank"),
        sa.UniqueConstraint(
            "workflow_id", "truth_table_hash", name="uq_hypothesis_workflow_semantics"
        ),
    )
    op.create_index(
        op.f("ix_accepted_hypotheses_workflow_id"),
        "accepted_hypotheses",
        ["workflow_id"],
        unique=False,
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "from_state",
            sa.Enum(
                "CREATED",
                "ANALYZING",
                "PROBE_READY",
                "AWAITING_RESPONSE",
                "RESPONSE_RECORDED",
                "RESUME_PENDING",
                "UPDATING",
                "AWAITING_REVIEW",
                "APPROVED",
                "EDITED",
                "REJECTED",
                "ABSTAINED",
                "FAILED",
                name="workflowstate",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_state",
            sa.Enum(
                "CREATED",
                "ANALYZING",
                "PROBE_READY",
                "AWAITING_RESPONSE",
                "RESPONSE_RECORDED",
                "RESUME_PENDING",
                "UPDATING",
                "AWAITING_REVIEW",
                "APPROVED",
                "EDITED",
                "REJECTED",
                "ABSTAINED",
                "FAILED",
                name="workflowstate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("event_key_hash", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id", "event_key_hash", name="uq_audit_workflow_event_key"),
        sa.UniqueConstraint("workflow_id", "sequence", name="uq_audit_workflow_sequence"),
    )
    op.create_index(
        op.f("ix_audit_events_workflow_id"), "audit_events", ["workflow_id"], unique=False
    )
    op.execute(
        """
        CREATE FUNCTION reject_audit_event_mutation() RETURNS trigger AS $$
        BEGIN
            IF TG_OP = 'DELETE' AND pg_trigger_depth() > 1 THEN
                RETURN OLD;
            END IF;
            RAISE EXCEPTION 'audit events are append-only';
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_events_append_only
        BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION reject_audit_event_mutation()
        """
    )
    op.create_table(
        "compiled_probes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("original_a", sa.Integer(), nullable=False),
        sa.Column("original_b", sa.Integer(), nullable=False),
        sa.Column("chosen_a", sa.Integer(), nullable=False),
        sa.Column("chosen_b", sa.Integer(), nullable=False),
        sa.Column("correct_prediction", sa.Integer(), nullable=False),
        sa.Column("specification_hash", sa.String(length=64), nullable=False),
        sa.Column("registry_version", sa.String(length=40), nullable=False),
        sa.Column("compiler_version", sa.String(length=48), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id"),
    )
    op.create_table(
        "generated_proposals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("generated_text", sa.Text(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id"),
    )
    op.create_table(
        "learner_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("derivation_nonce", sa.LargeBinary(length=32), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "octet_length(derivation_nonce) = 32",
            name="ck_learner_token_derivation_nonce_length",
        ),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
        sa.UniqueConstraint("workflow_id"),
    )
    op.create_index(
        op.f("ix_learner_tokens_expires_at"), "learner_tokens", ["expires_at"], unique=False
    )
    op.create_table(
        "model_calls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("model_id", sa.String(length=120), nullable=False),
        sa.Column("model_snapshot", sa.String(length=120), nullable=True),
        sa.Column("request_id", sa.String(length=160), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_calls_case_id"), "model_calls", ["case_id"], unique=False)
    op.create_index(
        op.f("ix_model_calls_workflow_id"), "model_calls", ["workflow_id"], unique=False
    )
    op.create_table(
        "teacher_reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("edited_text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id"),
    )
    op.create_table(
        "learner_responses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("learner_token_id", sa.UUID(), nullable=False),
        sa.Column("answer", sa.Integer(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("answer BETWEEN -10000 AND 10000", name="ck_response_answer"),
        sa.ForeignKeyConstraint(["learner_token_id"], ["learner_tokens.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("learner_token_id"),
        sa.UniqueConstraint("workflow_id"),
    )
    op.create_table(
        "probe_predictions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("compiled_probe_id", sa.UUID(), nullable=False),
        sa.Column("accepted_hypothesis_id", sa.UUID(), nullable=False),
        sa.Column("template_id", sa.String(length=64), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("prediction", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["accepted_hypothesis_id"], ["accepted_hypotheses.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["compiled_probe_id"], ["compiled_probes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("compiled_probe_id", "rank", name="uq_prediction_probe_rank"),
    )
    op.create_index(
        op.f("ix_probe_predictions_compiled_probe_id"),
        "probe_predictions",
        ["compiled_probe_id"],
        unique=False,
    )
    op.create_table(
        "learner_receipts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("learner_response_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key_hash", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_response_id"], ["learner_responses.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("learner_response_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS audit_events_append_only ON audit_events")
    op.execute("DROP FUNCTION IF EXISTS reject_audit_event_mutation()")
    op.drop_table("learner_receipts")
    op.drop_index(op.f("ix_probe_predictions_compiled_probe_id"), table_name="probe_predictions")
    op.drop_table("probe_predictions")
    op.drop_table("learner_responses")
    op.drop_table("teacher_reviews")
    op.drop_index(op.f("ix_model_calls_workflow_id"), table_name="model_calls")
    op.drop_index(op.f("ix_model_calls_case_id"), table_name="model_calls")
    op.drop_table("model_calls")
    op.drop_index(op.f("ix_learner_tokens_expires_at"), table_name="learner_tokens")
    op.drop_table("learner_tokens")
    op.drop_table("generated_proposals")
    op.drop_table("compiled_probes")
    op.drop_index(op.f("ix_audit_events_workflow_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_accepted_hypotheses_workflow_id"), table_name="accepted_hypotheses")
    op.drop_table("accepted_hypotheses")
    op.drop_index(op.f("ix_workflows_owner_id"), table_name="workflows")
    op.drop_table("workflows")
    op.drop_index(op.f("ix_idempotency_records_owner_id"), table_name="idempotency_records")
    op.drop_index(op.f("ix_idempotency_records_expires_at"), table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_index(op.f("ix_cases_owner_id"), table_name="cases")
    op.drop_table("cases")
    op.drop_table("owners")
    op.drop_table("deletion_audit_tombstones")
    # ### end Alembic commands ###
